language: go

jobs:
  include:
    - os: linux
      dist: bionic
      arch:
        - amd64
        - arm64
    - os: linux
      dist: xenial
      arch:
        - amd64
        - arm64
    - os: osx
      arch:
        - amd64
        - arm64

script: go version
